[general]
import = [ "./themes/tokyo-night.toml"]

[window]
padding.x = 10
padding.y = 10

opacity = 0.7
blur = true
decorations = "None"

option_as_alt = "Both"



[font]
normal.family = "JetBrainsMono Nerd Font"
size = 15
