brew "git"
brew "lazygit"
brew "neovim"
brew "stow"
brew "tldr"
brew "tree"
brew "ripgrep"
brew "fzf"
brew "npm"
brew "go"

cask "fork"
cask "ghostty"
cask "microsoft-auto-update"
cask "microsoft-excel"
cask "microsoft-teams"
cask "microsoft-word"
cask "raycast"
cask "rider"
cask "spotify"
cask "zen-browser"
cask 'discord'

cask "font-jetbrains-mono-nerd-font"
